modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/Phanton-Spawn-Overhaul/issues"
license = "MIT License"

[[mods]]
modId = "phantomspawnoverhaul"
version = "${version}"
displayName = "Phantom Spawn Overhaul"
authors = "JensenJ - Developer"
description = '''
A simple Minecraft mod which will provide an alternative path for phantoms to spawn. Allows phantoms to spawn on a player by using a potion of Insomnia.
'''

[[dependencies.phantomspawnoverhaul]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.phantomspawnoverhaul]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.phantomspawnoverhaul]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "phantomspawnoverhaul-neoforge.mixins.json"

[[mixins]]
config = "phantomspawnoverhaul-common.mixins.json"